from flask import Flask, render_template, request
import os
import pandas as pd
import pickle
import numpy as np
import tensorflow as tf
from PIL import Image
import io

# Setup Model Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, '..', 'models')

# Load Fertilizer Models
fertilizer_model = None
crop_encoder = None
try:
    fertilizer_model = pickle.load(open(os.path.join(MODELS_DIR, 'fertilizer_model.pkl'), 'rb'))
    crop_encoder = pickle.load(open(os.path.join(MODELS_DIR, 'crop_encoder.pkl'), 'rb'))
except Exception as e:
    print(f"Warning: Could not load fertilizer models. Error: {e}")

# Load Yield Models
yield_model = None
yield_crop_encoder = None
try:
    yield_model = pickle.load(open(os.path.join(MODELS_DIR, 'yield_model.pkl'), 'rb'))
    yield_crop_encoder = pickle.load(open(os.path.join(MODELS_DIR, 'yield_crop_encoder.pkl'), 'rb'))
except Exception as e:
    print(f"Warning: Could not load yield models. Error: {e}")

# Load Soil Model
soil_model = None
try:
    soil_model = pickle.load(open(os.path.join(MODELS_DIR, 'soil_model.pkl'), 'rb'))
except Exception as e:
    print(f"Warning: Could not load soil model. Error: {e}")

# Load Weather Crop Model
weather_model = None
try:
    weather_model = pickle.load(open(os.path.join(MODELS_DIR, 'weather_crop_model.pkl'), 'rb'))
except Exception as e:
    print(f"Warning: Could not load weather model. Error: {e}")

# Load Disease Model (Deep Learning)
disease_model = None
disease_classes = None
try:
    # Using .keras format
    disease_model = tf.keras.models.load_model(os.path.join(MODELS_DIR, 'disease_keras_model.keras'))
    disease_classes = pickle.load(open(os.path.join(MODELS_DIR, 'disease_classes.pkl'), 'rb'))
except Exception as e:
    print(f"Warning: Could not load disease model. Error: {e}")


app = Flask(__name__)

# --- UTILS (Mock Logic for Demo) ---
# 1. Fertilizer Logic (ML Integrated)
def recommend_fertilizer_logic(n, p, k, crop):
    if fertilizer_model is None or crop_encoder is None:
        return "Model Not Loaded", "Please train the model first."
    
    # The crop coming from frontend is already formatted correctly as per Kaggle classes
    # e.g., 'Ground Nuts', 'Paddy', 'Wheat', etc.
    # Check if we have seen this crop before in our encoder
    if crop not in crop_encoder.classes_:
        return "Unknown Crop", f"Crop '{crop}' is not supported yet."
        
    encoded_crop = crop_encoder.transform([crop])[0]
    
    # The Kaggle dataset feature order: Nitrogen, Phosphorous, Potassium, Crop Type
    prediction = fertilizer_model.predict([[n, p, k, encoded_crop]])
    
    return prediction[0], "Prediction generated by AI Model based on N-P-K and Crop Type."

# 2. Crop Yield Logic (ML Integrated)
def predict_yield_logic(crop, area, rain, temp):
    if yield_model is None or yield_crop_encoder is None:
        return "Model Not Loaded", "Please train the yield model first."
        
    try:
        # Check if crop is recognized
        if crop not in yield_crop_encoder.classes_:
            return "Unknown Crop", f"Crop '{crop}' is not supported yet."
            
        encoded_crop = yield_crop_encoder.transform([crop])[0]
        
        # Ensure variables are floats
        area = float(area)
        rain = float(rain)
        temp = float(temp)
        
        # Features: Crop (encoded), Area, Rainfall, Temperature
        # Important: Order must match the X_train in train_yield.py
        prediction = yield_model.predict([[encoded_crop, area, rain, temp]])
        
        # Round prediction
        total_yield_tonnes = round(prediction[0], 2)
        
        message = f"Predicted using AI Regressor for {area} hectares of {crop}."
        return total_yield_tonnes, message
    except Exception as e:
        return "Error", f"Could not process: {e}"

# 3. Soil Quality Logic (ML Integrated)
def predict_soil_logic(n, p, k, ph):
    if soil_model is None:
        return "Model Not Loaded", "Please train the soil classifier first."
        
    try:
        n = float(n)
        p = float(p)
        k = float(k)
        ph = float(ph)
        
        # Features: Nitrogen, Phosphorus, Potassium, ph
        prediction = soil_model.predict([[n, p, k, ph]])
        
        predicted_class = prediction[0]
        
        # Generating a dynamic message
        if predicted_class == "Fertile":
            message = "Excellent! The nutrient levels and pH are optimal for agriculture."
        elif predicted_class == "Medium":
            message = "Moderate soil health. Consider mild fertilization to improve crop yield."
        else:
            message = "Poor soil quality. Strong soil treatment and fertilization are highly recommended."
            
        return predicted_class, message
    except Exception as e:
        return "Error", f"Could not process: {e}"

# 4. Weather Crop Logic (ML Integrated)
def predict_weather_crop_logic(temp, humid, rain):
    if weather_model is None:
        return "Model Not Loaded", "Please train the weather crop classifier first."
        
    try:
        temp = float(temp)
        humid = float(humid)
        rain = float(rain)
        
        # Features: Temperature, Humidity, Rainfall
        prediction = weather_model.predict([[temp, humid, rain]])
        
        predicted_crop = prediction[0]
        
        return predicted_crop, f"AI Suggestion based on Temp: {temp}°C, Humidity: {humid}%, Rain: {rain}mm."
    except Exception as e:
        return "Error", f"Could not process: {e}"

# 5. Disease Logic (ML Integrated - CNN)
def predict_disease_logic(image_file):
    if disease_model is None or disease_classes is None:
        return "Model Not Loaded", "Please train the disease model first."
        
    try:
        # Read image to PIL and resize to match training (64x64)
        img = Image.open(image_file).convert('RGB')
        img = img.resize((64, 64))
        
        # Convert to numpy array and normalize
        img_array = np.array(img) / 255.0
        
        # Add batch dimension (model expects shape [None, 64, 64, 3])
        img_array = np.expand_dims(img_array, axis=0)
        
        # Predict
        predictions = disease_model.predict(img_array)
        class_idx = np.argmax(predictions[0])
        confidence = float(np.max(predictions[0]))
        
        result = disease_classes[class_idx]
        
        recommendations = {
            "Apple Scab": "Fungal infection. Prune affected branches and apply fungicide.",
            "Corn Common Rust": "Treat with sulfur-based fungicides and improve air circulation.",
            "Potato Early Blight": "Remove infected leaves and apply copper-based fungicides.",
            "Healthy Crop": "No issues detected. Maintain regular watering and nutrient balance."
        }
        
        msg = recommendations.get(result, "Maintain crop health and monitor closely.")
        full_msg = f"{msg} (AI Confidence: {confidence*100:.2f}%)"
        
        return result, full_msg
    except Exception as e:
        return "Error", f"Failed to process image: {e}"

# --- ROUTES ---

@app.route('/')
def home():
    return render_template('index.html')

# 1. Fertilizer Module
@app.route('/fertilizer')
def fertilizer():
    return render_template('fertilizer.html', result=None)

@app.route('/predict-fertilizer', methods=['POST'])
def predict_fertilizer():
    try:
        n = int(request.form['nitrogen'])
        p = int(request.form['phosphorus'])
        k = int(request.form['potassium'])
        crop = request.form['crop']
        prediction, msg = recommend_fertilizer_logic(n, p, k, crop)
        return render_template('fertilizer.html', result=prediction, message=msg)
    except Exception as e:
        return render_template('fertilizer.html', result="Error", message=str(e))

# 2. Crop Yield Module
@app.route('/crop-yield')
def crop_yield():
    return render_template('crop_yield.html', result=None)

@app.route('/predict-yield', methods=['POST'])
def predict_yield():
    try:
        crop = request.form['crop']
        area = request.form['area']
        rainfall = request.form['rainfall']
        temperature = request.form['temperature']
        
        prediction, msg = predict_yield_logic(crop, area, rainfall, temperature)
        return render_template('crop_yield.html', result=prediction, message=msg)
    except Exception as e:
        return render_template('crop_yield.html', result="Error", message=str(e))

# 3. Soil Quality Module
@app.route('/soil-quality')
def soil_quality():
    return render_template('soil_quality.html', result=None)

@app.route('/predict-soil', methods=['POST'])
def predict_soil():
    try:
        n = float(request.form['nitrogen'])
        p = float(request.form['phosphorus'])
        k = float(request.form['potassium'])
        ph = float(request.form['ph'])
        
        prediction, msg = predict_soil_logic(n, p, k, ph)
        return render_template('soil_quality.html', result=prediction, message=msg)
    except Exception as e:
        return render_template('soil_quality.html', result="Error", message=str(e))

# 4. Disease Detection Module
@app.route('/disease')
def disease():
    return render_template('disease.html', result=None)

@app.route('/predict-disease', methods=['POST'])
def predict_disease():
    try:
        if 'image' not in request.files:
            return render_template('disease.html', result="Error", message="No image uploaded")
        
        file = request.files['image']
        if file.filename == '':
            return render_template('disease.html', result="Error", message="No image selected")

        # Save file logic would go here
        # file.save(os.path.join('static/uploads', file.filename))
        
        prediction, msg = predict_disease_logic(file)
        return render_template('disease.html', result=prediction, message=msg)
    except Exception as e:
        return render_template('disease.html', result="Error", message=str(e))

# 5. Weather Crop Module
@app.route('/weather')
def weather():
    return render_template('weather.html', result=None)

@app.route('/predict-weather-crop', methods=['POST'])
def predict_weather_crop():
    try:
        temp = float(request.form['temperature'])
        humid = float(request.form['humidity'])
        rain = float(request.form['rainfall'])
        
        prediction, msg = predict_weather_crop_logic(temp, humid, rain)
        return render_template('weather.html', result=prediction, message=msg)
    except Exception as e:
        return render_template('weather.html', result="Error", message=str(e))

if __name__ == '__main__':
    app.run(debug=True, port=5000)
